parameters:
#    down_the_spot_site.example.class: DownTheSpot\SiteBundle\Example

services:
    down_the_spot_site.getlink:
        class: DownTheSpot\SiteBundle\Services\GetLink
#        arguments: [@service_id, "plain_value", %parameter%]
